server:
  port: 8080

spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      routes:
        - id: calendar
          uri: http://calendar-diary-server-svc.apps.svc.cluster.local:8080
          predicates:
            - Path=/calendar/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Prefix, /calendar
            - AddRequestHeader=X-Forwarded-Proto, http   # https면 https


        - id: user
          uri: http://userserver-svc.apps.svc.cluster.local:8080
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Prefix, /user
            - AddRequestHeader=X-Forwarded-Proto, http   # https면 https

        - id: health
          uri: http://healthserver-svc.apps.svc.cluster.local:8080
          predicates:
            - Path=/health/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Prefix, /health
            - AddRequestHeader=X-Forwarded-Proto, http   # https면 https

    config:
      enabled: true
      uri: ${SPRING_CONFIG_IMPORT}

  config:
    import: "configserver:"

eureka:
  client:
    enabled: true  # Eureka 클라이언트 활성화
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}


springdoc:
  swagger-ui:
    path: /swagger-ui                # 공용 UI 경로 (원하면 /docs 로 바꿔도 됨)
    display-request-duration: true
    urls:
      - name: calendar
        url: /calendar/v3/api-docs

      - name: user
        url: /user/v3/api-docs

      - name: health
        url: /health/v3/api-docs



#  cloud:
#    config:
#      uri: http://config-server:8888  # localhost → config-server로 변경
#         uri: ${CONFIG_SERVER_URL}:8888 # 환경변수로 설정


#eureka:
#  client:
#    service-url:
#      defaultZone: http://eurekaserver-svc:8761/eureka


#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    urls:
#      - name: tangram-server
#        #        url: ${CONFIG_SERVER_URL}:8082/v3/api-docs
#        url: /tangram-server/v3/api-docs
#      - name: user-server

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    probes:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true