apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  namespace: apps
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web  # 80
    # TLS 쓸 때는 websecure로 바꾸고 cert-manager 추가
spec:
  rules:
  - host: api.43.203.238.139.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gatewayserver-svc
            port: { number: 8080 }
