apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  namespace: apps
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels: { app: configserver }
  template:
    metadata:
      labels: { app: configserver }
    spec:
      imagePullSecrets:
      - name: dockerhub-cred
      terminationGracePeriodSeconds: 30
      containers:
      - name: configserver
        image: docker.io/opensongce/msa:configserver-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        envFrom:
        - secretRef:
            name: configserver-git
        readinessProbe:
          httpGet: { path: /actuator/health/readiness, port: 8888 }
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /actuator/health/liveness,  port: 8888 }
          initialDelaySeconds: 30
          periodSeconds: 10
        lifecycle:
          preStop:
            exec: { command: ["sh","-lc","sleep 5"] }
