apiVersion: v1
kind: Namespace
metadata: { name: apps }
---
apiVersion: v1
kind: Namespace
metadata: { name: data }
---
apiVersion: v1
kind: Namespace
metadata: { name: observability }
---
apiVersion: v1
kind: Namespace
metadata: { name: ingress }
