apiVersion: v1
kind: Service
metadata:
  name: calendar-diary-server-svc
  namespace: apps
spec:
  selector:
    app: calendar-diary-server
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
