
spring:
  application:
    name: "calendar-diary-server"
  config:
    # Config Server에서 원격 설정을 끌어오도록 지시 (필수)
    import: "configserver:"

#
#  jpa:
#    hibernate:
#      ddl-auto: update        # create / update / validate / none 중 선택
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#        show_sql: true

  cloud:
    # K8s 서비스 DNS로 Config Server 위치 명시
    config:
      uri: http://configserver-svc:8888
      enabled: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/calendar_diary   # DB 이름에 맞게 수정
#    username: postgres                                   # 본인 PostgreSQL 계정
#    password: root                                       # 실제 비밀번호
#    driver-class-name: org.postgresql.Driver
#
#eureka:
#  client:
#    enabled: false

